<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XMAMan.GraphicEngine2D" Version="0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhysicGlobal\PhysicGlobal.csproj" />
  </ItemGroup>

</Project>
