<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JsonHelper\JsonHelper.csproj" />
    <ProjectReference Include="..\KeyFrameGlobal\KeyFrameGlobal.csproj" />
    <ProjectReference Include="..\LevelEditorExports\LevelEditorExports.csproj" />
    <ProjectReference Include="..\RigidBodyPhysics\RigidBodyPhysics.csproj" />
    <ProjectReference Include="..\TextureEditorGlobal\TextureEditorGlobal.csproj" />
    <ProjectReference Include="..\TexturePhysicImporter\TexturePhysicImporter.csproj" />
  </ItemGroup>

</Project>
