<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Editor\KeyboardMappings\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyFrameGlobal\KeyFrameGlobal.csproj" />
    <ProjectReference Include="..\RigidBodyPhysics\RigidBodyPhysics.csproj" />
    <ProjectReference Include="..\TextureEditorGlobal\TextureEditorGlobal.csproj" />
  </ItemGroup>

</Project>
