<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="ReactiveUI" Version="20.2.45" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
    <PackageReference Include="ReactiveUI.WPF" Version="20.2.45" />
    <PackageReference Include="XMAMan.GraphicEngine" Version="0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameHelper\GameHelper.csproj" />
    <ProjectReference Include="..\JsonHelper\JsonHelper.csproj" />
    <ProjectReference Include="..\WpfControls\WpfControls.csproj" />
  </ItemGroup>

</Project>
