cd ../Source/
cd .vs && rmdir /S /Q . 2>nul & cd ..
cd AstroidsControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd AstroidsControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd BridgeBuilderControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd BridgeBuilderControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd CarDrifterControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd CarDrifterControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd DemoApplications.UnitTests/bin && rmdir /S /Q . 2>nul & cd ../..
cd DemoApplications.UnitTests/obj && rmdir /S /Q . 2>nul & cd ../..
cd DynamicObjCreation/bin && rmdir /S /Q . 2>nul & cd ../..
cd DynamicObjCreation/obj && rmdir /S /Q . 2>nul & cd ../..
cd DynamicObjCreation.UnitTests/bin && rmdir /S /Q . 2>nul & cd ../..
cd DynamicObjCreation.UnitTests/obj && rmdir /S /Q . 2>nul & cd ../..
cd ElmaControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd ElmaControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd GameHelper/bin && rmdir /S /Q . 2>nul & cd ../..
cd GameHelper/obj && rmdir /S /Q . 2>nul & cd ../..
cd JsonHelper/bin && rmdir /S /Q . 2>nul & cd ../..
cd JsonHelper/obj && rmdir /S /Q . 2>nul & cd ../..
cd KeyboardRecordAndPlay/bin && rmdir /S /Q . 2>nul & cd ../..
cd KeyboardRecordAndPlay/obj && rmdir /S /Q . 2>nul & cd ../..
cd KeyFrameEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd KeyFrameEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd KeyFrameGlobal/bin && rmdir /S /Q . 2>nul & cd ../..
cd KeyFrameGlobal/obj && rmdir /S /Q . 2>nul & cd ../..
cd KeyFramePhysicImporter/bin && rmdir /S /Q . 2>nul & cd ../..
cd KeyFramePhysicImporter/obj && rmdir /S /Q . 2>nul & cd ../..
cd LevelEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd LevelEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd LevelEditorGlobal/bin && rmdir /S /Q . 2>nul & cd ../..
cd LevelEditorGlobal/obj && rmdir /S /Q . 2>nul & cd ../..
cd LevelToSimulatorConverter/bin && rmdir /S /Q . 2>nul & cd ../..
cd LevelToSimulatorConverter/obj && rmdir /S /Q . 2>nul & cd ../..
cd MoonlanderControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd MoonlanderControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicEngine/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicEngine/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicItemEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicItemEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneDrawing/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneDrawing/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneKeyboardControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneKeyboardControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneSimulatorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneSimulatorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneTestbedControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd PhysicSceneTestbedControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd RigidBodyPhysics/bin && rmdir /S /Q . 2>nul & cd ../..
cd RigidBodyPhysics/obj && rmdir /S /Q . 2>nul & cd ../..
cd RigidBodyPhysics.UnitTests/bin && rmdir /S /Q . 2>nul & cd ../..
cd RigidBodyPhysics.UnitTests/obj && rmdir /S /Q . 2>nul & cd ../..
cd Simulator/bin && rmdir /S /Q . 2>nul & cd ../..
cd Simulator/obj && rmdir /S /Q . 2>nul & cd ../..
cd SkiJumperControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd SkiJumperControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd SpriteEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd SpriteEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd TextureEditorControl/bin && rmdir /S /Q . 2>nul & cd ../..
cd TextureEditorControl/obj && rmdir /S /Q . 2>nul & cd ../..
cd TextureEditorGlobal/bin && rmdir /S /Q . 2>nul & cd ../..
cd TextureEditorGlobal/obj && rmdir /S /Q . 2>nul & cd ../..
cd TexturePhysicImporter/bin && rmdir /S /Q . 2>nul & cd ../..
cd TexturePhysicImporter/obj && rmdir /S /Q . 2>nul & cd ../..
cd WpfControls/bin && rmdir /S /Q . 2>nul & cd ../..
cd WpfControls/obj && rmdir /S /Q . 2>nul & cd ../..