<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LevelToSimulatorConverter\LevelToSimulatorConverter.csproj" />
    <ProjectReference Include="..\PhysicSceneDrawing\PhysicSceneDrawing.csproj" />
    <ProjectReference Include="..\PhysicSceneKeyboardControl\PhysicSceneKeyboardControl.csproj" />
    <ProjectReference Include="..\PhysicSceneToAnimationConverter\PhysicSceneToAnimationConverter.csproj" />
  </ItemGroup>

</Project>
