<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicObjCreation\DynamicObjCreation.csproj" />
    <ProjectReference Include="..\KeyboardRecordAndPlay\KeyboardRecordAndPlay.csproj" />
    <ProjectReference Include="..\LevelToSimulatorConverter\LevelToSimulatorConverter.csproj" />
    <ProjectReference Include="..\RigidBodyPhysics\RigidBodyPhysics.csproj" />
    <ProjectReference Include="..\Simulator\Simulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="XMAMan.GraphicEngine" Version="0.0.2" />
  </ItemGroup>

</Project>
