<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
	<OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
    <Page Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="View\Pause.png" />
    <None Remove="View\Play.PNG" />
    <None Remove="View\Restart.png" />
    <None Remove="View\SingleStep.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="19.4.1" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.4.1" />
    <PackageReference Include="ReactiveUI.WPF" Version="19.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlInterfaces\ControlInterfaces.csproj" />
    <ProjectReference Include="..\EditorControl\EditorControl.csproj" />
    <ProjectReference Include="..\JsonHelper\JsonHelper.csproj" />
    <ProjectReference Include="..\PhysicEngine\PhysicEngine.csproj" />
    <ProjectReference Include="..\SimulatorControl\SimulatorControl.csproj" />
  </ItemGroup>

</Project>
